In [1]:
import pandas as pd
import numpy as np

In [2]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [3]:
df = pd.read_csv(titanic_dataset_github_url)

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df_passenger_id = df.set_index("PassengerId")
df_passenger_id.head(2)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [6]:
df_name = df.set_index('Name')
df_name.head(3)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [10]:
df.loc["Braund, Mr. Owen Harris"]

KeyError: 'Braund, Mr. Owen Harris'

In [9]:
df_name.loc['Braund, Mr. Owen Harris']

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                 22.0
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
subset = df[df['Sex'] == 'male']
subset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [13]:
subset['Age'] = subset['Age'] + 1
subset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S

In [16]:
# This will be more Safer

subset = df[df['Sex'] == 'male'].copy()
subset['Age'] = subset['Age'] + 1
subset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### set index vs reindex()

In [18]:
df_name = df.set_index('Name')
df_name.head(3)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [20]:
df_name.loc["Heikkinen, Miss. Laina"]

PassengerId                   3
Survived                      1
Pclass                        3
Sex                      female
Age                        26.0
SibSp                         0
Parch                         0
Ticket         STON/O2. 3101282
Fare                      7.925
Cabin                       NaN
Embarked                      S
Name: Heikkinen, Miss. Laina, dtype: object

In [21]:
df_name = df_name.reset_index()
df_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
sales_jan = pd.DataFrame([100, 200, 300] , index=["Store_A" , "Store_B" , "Store_C"] , columns=["Sales"])
sales_jan

         Sales
Store_A    100
Store_B    200
Store_C    300

In [28]:
sales_feb = pd.DataFrame([110, 350] , index=["Store_A" , "Store_C"] , columns=["Sales"])
sales_feb

         Sales
Store_A    110
Store_C    350

In [29]:
common_index = sales_jan.index
print(common_index)

Index(['Store_A', 'Store_B', 'Store_C'], dtype='str')

In [30]:
sales_feb_aligned = sales_feb.reindex(common_index)
sales_feb_aligned

         Sales
Store_A  110.0
Store_B    NaN
Store_C  350.0

In [31]:
sales_diff = sales_feb_aligned["Sales"] - sales_jan["Sales"]
sales_diff

Store_A    10.0
Store_B     NaN
Store_C    50.0
Name: Sales, dtype: float64

In [32]:
sales_feb_aligned = sales_feb.reindex(common_index , fill_value = 0)
sales_feb_aligned

         Sales
Store_A    110
Store_B      0
Store_C    350

In [33]:
sales_diff = sales_feb_aligned["Sales"] - sales_jan["Sales"]
sales_diff

Store_A     10
Store_B   -200
Store_C     50
Name: Sales, dtype: int64

In [35]:
source_a = pd.DataFrame({
  "Product" : ["Laptop", "Ipad" , "Mobile"],
  "Price" : [10000 , 10000 , 1000],
  "Stock" : [23, 45, 67]
})

In [36]:
source_a

  Product  Price  Stock
0  Laptop  10000     23
1    Ipad  10000     45
2  Mobile   1000     67

In [37]:
source_b = pd.DataFrame({
  "Product" : ["Laptop", "Ipad" , "Mobile"],
  "Price" : [999999 , 78390 , 2345]
})

In [38]:
source_b

  Product   Price
0  Laptop  999999
1    Ipad   78390
2  Mobile    2345

In [39]:
stock_diff = source_a["Stock"] - source_b["Stock"]

KeyError: 'Stock'

In [40]:
common_coumns = source_a.columns
print(common_coumns)

Index(['Product', 'Price', 'Stock'], dtype='str')

In [41]:
source_b_aligned = source_b.reindex(columns = common_coumns , fill_value = 0)
source_b_aligned

  Product   Price  Stock
0  Laptop  999999      0
1    Ipad   78390      0
2  Mobile    2345      0

In [43]:
stock_diff = source_a["Stock"] - source_b_aligned["Stock"]
stock_diff

0    23
1    45
2    67
Name: Stock, dtype: int64

### Iterating in pandas

In [5]:
data = pd.DataFrame({
  "Name" : ["Manoj" , "Ram" , "Sai"],
  "Age" : [26 , 32 , 31],
  "City" : ["Hyderabad" , "Chennai" , "Banglore"]
})

In [6]:
data

    Name  Age       City
0  Manoj   26  Hyderabad
1    Ram   32    Chennai
2    Sai   31   Banglore

In [7]:
for index, row in data.iterrows():
  print(f"{index} : {row["Name"]} lives in {row["City"]} and of {row["Age"]} years old")

0 : Manoj lives in Hyderabad and of 26 years old
1 : Ram lives in Chennai and of 32 years old
2 : Sai lives in Banglore and of 31 years old

In [8]:
for row in data.itertuples():
  print(row)
  print(f"{row.Index} : {row.Name} lives in {row.City} and of {row.Age} years old", end = "\n\n")

Pandas(Index=0, Name='Manoj', Age=26, City='Hyderabad')
0 : Manoj lives in Hyderabad and of 26 years old

Pandas(Index=1, Name='Ram', Age=32, City='Chennai')
1 : Ram lives in Chennai and of 32 years old

Pandas(Index=2, Name='Sai', Age=31, City='Banglore')
2 : Sai lives in Banglore and of 31 years old

In [9]:
for col in data.columns:
  print(f"Column : {col}")
  print(data[col].values , end = "\n\n")

Column : Name
<StringArray>
['Manoj', 'Ram', 'Sai']
Length: 3, dtype: str

Column : Age
[26 32 31]

Column : City
<StringArray>
['Hyderabad', 'Chennai', 'Banglore']
Length: 3, dtype: str

In [10]:
list(data.columns)

['Name', 'Age', 'City']

In [11]:
data

    Name  Age       City
0  Manoj   26  Hyderabad
1    Ram   32    Chennai
2    Sai   31   Banglore

### Conditional Example: Adding Column with custom logic

In [18]:
categories = []
for index, row in data.iterrows():
  if row["Age"] < 30:
    categories.append("Student")
  else:
    categories.append("Employee")

In [19]:
print(categories)

['Student', 'Employee', 'Employee']

In [21]:
data["Categories"] = categories
data

    Name  Age       City Categories
0  Manoj   26  Hyderabad    Student
1    Ram   32    Chennai   Employee
2    Sai   31   Banglore   Employee

In [22]:
data["Categories_1"] = data["Age"].apply(lambda age: "Student" if age < 30 else "Employee")

In [23]:
data

    Name  Age       City Categories Categories_1
0  Manoj   26  Hyderabad    Student      Student
1    Ram   32    Chennai   Employee     Employee
2    Sai   31   Banglore   Employee     Employee

In [24]:
lambda_age = lambda age : "Student" if age < 30 else "Employee"
data["Categories_2"] = data["Age"].apply(lambda_age)
data

    Name  Age       City Categories Categories_1 Categories_2
0  Manoj   26  Hyderabad    Student      Student      Student
1    Ram   32    Chennai   Employee     Employee     Employee
2    Sai   31   Banglore   Employee     Employee     Employee

In [25]:
def category_check(age):
  if age < 30:
    return "Student"
  else:
    return "Employee"

In [28]:
data["Categories_3"] = data["Age"].apply(category_check)
data

    Name  Age       City Categories Categories_1 Categories_2 Categories_3
0  Manoj   26  Hyderabad    Student      Student      Student      Student
1    Ram   32    Chennai   Employee     Employee     Employee     Employee
2    Sai   31   Banglore   Employee     Employee     Employee     Employee

In [36]:
def check_is_hyd_and_young(row):
  city = row["City"]
  age = row["Age"]
  if city == "Hyderabad":
    if age < 30:
      return True
    else:
      return False
  return False

In [37]:
data["is_hyd_and_young"] = data.apply(check_is_hyd_and_young, axis = 1)

In [38]:
data

,Name,Age,City,Categories,Categories_1,Categories_2,Categories_3,is_hyd_and_young
0,Manoj,26,Hyderabad,Student,Student,Student,Student,True
1,Ram,32,Chennai,Employee,Employee,Employee,Employee,False
2,Sai,31,Banglore,Employee,Employee,Employee,Employee,False

In [40]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [43]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [44]:
sorted_df = df.sort_values(by = "Age" , axis = 0 , ascending = True)

In [46]:
sorted_df[["Name" , "Age"]].head(10)

                                Name   Age
803  Thomas, Master. Assad Alexander  0.42
755        Hamalainen, Master. Viljo  0.67
644           Baclini, Miss. Eugenie  0.75
469    Baclini, Miss. Helene Barbara  0.75
78     Caldwell, Master. Alden Gates  0.83
831  Richards, Master. George Sibley  0.83
305   Allison, Master. Hudson Trevor  0.92
386  Goodwin, Master. Sidney Leonard  1.00
172     Johnson, Miss. Eleanor Ileen  1.00
183        Becker, Master. Richard F  1.00

In [47]:
sorted_df[["Name" , "Age"]].tail(10)

                                             Name  Age
832                                Saad, Mr. Amin  NaN
837                           Sirota, Mr. Maurice  NaN
839                          Marechal, Mr. Pierre  NaN
846                      Sage, Mr. Douglas Bullen  NaN
849  Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  NaN
859                              Razi, Mr. Raihed  NaN
863             Sage, Miss. Dorothy Edith "Dolly"  NaN
868                   van Melkebeke, Mr. Philemon  NaN
878                            Laleff, Mr. Kristo  NaN
888      Johnston, Miss. Catherine Helen "Carrie"  NaN

In [48]:
sorted_df.iloc[200:300 , :]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
491,492,0,3,"Windelov, Mr. Einar",male,21.0,0,0,SOTON/OQ 3101317,7.2500,NaN,S
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.0,0,0,54636,16.1000,NaN,S
836,837,0,3,"Pasic, Mr. Jakob",male,21.0,0,0,315097,8.6625,NaN,S
501,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q
395,396,0,3,"Johansson, Mr. Erik",male,22.0,0,0,350052,7.7958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
370,371,1,1,"Harder, Mr. George Achilles",male,25.0,1,0,11765,55.4417,E50,C
784,785,0,3,"Ali, Mr. William",male,25.0,0,0,SOTON/O.Q. 3101312,7.0500,NaN,S
134,135,0,2,"Sobey, Mr. Samuel James Hayden",male,25.0,0,0,C.A. 29178,13.0000,NaN,S
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.0,0,0,348123,7.6500,F G73,S

In [50]:
df["Age"].dtype

dtype('float64')

In [53]:
df["Age"] = df["Age"].astype("int64")

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer.Replace or remove non-finite values or cast to an integer typethat supports these values (e.g. 'Int64')

In [54]:
df["Age"] = df["Age"].fillna(0).astype("int64")

In [55]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,0,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,NaN,C

In [56]:
print(df[["Name", "Age"]].tail(8))

                                         Name  Age
883             Banfield, Mr. Frederick James   28
884                    Sutehall, Mr. Henry Jr   25
885      Rice, Mrs. William (Margaret Norton)   39
886                     Montvila, Rev. Juozas   27
887              Graham, Miss. Margaret Edith   19
888  Johnston, Miss. Catherine Helen "Carrie"    0
889                     Behr, Mr. Karl Howell   26
890                       Dooley, Mr. Patrick   32

In [58]:
sorted_df = df.sort_values(by = "Age")
sorted_df[["Name", "Age"]].tail(10)

                                     Name  Age
456             Millet, Mr. Francis Davis   65
280                      Duane, Mr. Frank   65
33                  Wheadon, Mr. Edward H   66
116                  Connors, Mr. Patrick   70
745          Crosby, Capt. Edward Gifford   70
672           Mitchell, Mr. Henry Michael   70
493               Artagaveytia, Mr. Ramon   71
96              Goldschmidt, Mr. George B   71
851                   Svensson, Mr. Johan   74
630  Barkworth, Mr. Algernon Henry Wilson   80

In [59]:
### Sorting by multiple Columns

df_sorted_1 = df.sort_values(by = ["Pclass" , "Fare"] , ascending  = [True, False])

In [60]:
df_sorted_1.head(7)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35,0,0,PC 17755,512.3292,B101,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19,3,2,19950,263.0000,C23 C25 C27,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23,3,2,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64,1,4,19950,263.0000,C23 C25 C27,S

### Sort_index

In [61]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,NaN,Q

In [62]:
df_sort_2 = df.set_index("PassengerId")
df_sort_2

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,NaN,Q

In [63]:
df_sort_index = df_sort_2.sort_index()
df_sort_index.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [64]:
# Sorting Columns alphabetically

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [65]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [67]:
columns_sorted_df = df[sorted(df.columns)]

In [68]:
columns_sorted_df.head(5)

,Age,Cabin,Embarked,Fare,Name,Parch,PassengerId,Pclass,Sex,SibSp,Survived,Ticket
0,22,NaN,S,7.2500,"Braund, Mr. Owen Harris",0,1,3,male,1,0,A/5 21171
1,38,C85,C,71.2833,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,2,1,female,1,1,PC 17599
2,26,NaN,S,7.9250,"Heikkinen, Miss. Laina",0,3,3,female,0,1,STON/O2. 3101282
3,35,C123,S,53.1000,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,4,1,female,1,1,113803
4,35,NaN,S,8.0500,"Allen, Mr. William Henry",0,5,3,male,0,0,373450

### Working with text Data in pandas

In [69]:
df["Name"].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [70]:
df["Name"].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [71]:
df["Name"].str.len()

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [72]:
df["Name"].str.capitalize()

0                                Braund, mr. owen harris
1      Cumings, mrs. john bradley (florence briggs th...
2                                 Heikkinen, miss. laina
3           Futrelle, mrs. jacques heath (lily may peel)
4                               Allen, mr. william henry
                             ...
886                                Montvila, rev. juozas
887                         Graham, miss. margaret edith
888             Johnston, miss. catherine helen "carrie"
889                                Behr, mr. karl howell
890                                  Dooley, mr. patrick
Name: Name, Length: 891, dtype: str