In [1]:
import pandas as pd
import numpy as np

In [14]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [15]:
df = pd.read_csv(titanic_dataset_github_url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df["Name"].str.replace("Mr." , "Sir" , regex = False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [7]:
df["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [11]:
df.loc[1]["Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [12]:
df.loc[1, "Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [14]:
start = df.loc[1, "Name"].find("(")
start

27

In [15]:
end = df.loc[1, "Name"].find(")")
end

50

In [21]:
name = df.loc[1, "Name"][:start] + df.loc[1, "Name"][end + 1 : ]
name

'Cumings, Mrs. John Bradley '

In [24]:
df["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [28]:
def remove_substring(name):
  start = name.find("(")
  end = name.find(")")
  new_name = name[:start] + name[end + 1:]
  new_name = new_name.strip()
  return new_name

In [29]:
df["Name_Trimmed"] = df["Name"].apply(remove_substring)

In [30]:
df["Name_Trimmed"].head(5)

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_Trimmed, dtype: str

In [31]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Name_Trimmed'],
      dtype='str')

In [32]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [33]:
df["Name"].replace(r"\(.*\)" , "HELLO" , regex = True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley HELLO
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath HELLO
4              Allen, Mr. William Henry
Name: Name, dtype: str

In [34]:
df["Name"].replace(r"\(.*\)" , "" , regex = True).head()

0          Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henry
Name: Name, dtype: str

### Split and Access Elements

In [35]:
df["Name"][0]

'Braund, Mr. Owen Harris'

In [ ]:
df["Name"].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [38]:
df["Name"].str.split(" ")[0]

['Braund,', 'Mr.', 'Owen', 'Harris']

In [39]:
df["Name"].str.split(" ").str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

### Strip Spaces

In [40]:
df["Name"][0]

'Braund, Mr. Owen Harris'

In [42]:
df["Name"].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [43]:
df["Name"].str.lstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [44]:
df["Name"].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

### Find Poisition of substring

In [45]:
df["Name"].str.find("Mr.")

0      8
1     -1
2     -1
3     -1
4      7
      ..
886   -1
887   -1
888   -1
889    6
890    8
Name: Name, Length: 891, dtype: int64

In [46]:
df["Name"].str.contains("Mr.")

0       True
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889     True
890     True
Name: Name, Length: 891, dtype: bool

In [48]:
count = df["Name"].str.contains("Mr.").sum()
print(count)

647

In [49]:
data = pd.DataFrame({
  "Name" : ["Manoj", "Sai" , "Ravi" , "Pavan" , "Sonu"],
  "email" : ["man@gmail.com", "s@gmail.com" , "pas@gmail.com" , "rav@gmail.com" , "xc@gmail.com"]
})

In [50]:
data

    Name          email
0  Manoj  man@gmail.com
1    Sai    s@gmail.com
2   Ravi  pas@gmail.com
3  Pavan  rav@gmail.com
4   Sonu   xc@gmail.com

In [51]:
data["Name"].str.pad(width = 15, fillchar = "*" , side = "left")

0    **********Manoj
1    ************Sai
2    ***********Ravi
3    **********Pavan
4    ***********Sonu
Name: Name, dtype: str

### Categorical data in Pandas

In [2]:
class_data = {
  "Names" : ["A" , "B" , "C" , "D"],
  "Groups" : ["G1" , "G3" , "G4" , "G2"]
}

In [3]:
class_df = pd.DataFrame(class_data)

In [4]:
class_df

  Names Groups
0     A     G1
1     B     G3
2     C     G4
3     D     G2

In [5]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   4 non-null      str
 1   Groups  4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [6]:
class_df["Groups_Cat"] = pd.Categorical(class_df["Groups"],
                                        categories = ["G1", "G2" , "G3" , "G4"],
                                        ordered = True)

In [7]:
class_df

  Names Groups Groups_Cat
0     A     G1         G1
1     B     G3         G3
2     C     G4         G4
3     D     G2         G2

In [8]:
class_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Names       4 non-null      str
 1   Groups      4 non-null      str
 2   Groups_Cat  4 non-null      category
dtypes: category(1), str(2)
memory usage: 404.0 bytes

In [9]:
class_df["Groups_Cat"].cat.categories

Index(['G1', 'G2', 'G3', 'G4'], dtype='str')

In [11]:
class_df["Groups_Cat"] >= "G4"

0    False
1    False
2     True
3    False
Name: Groups_Cat, dtype: bool

In [17]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [19]:
df["Embarked"].unique()  # the port where the passenger boarded the ship indicated by a single letter code.

<StringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [20]:
df["Embarked"] = df["Embarked"].fillna("N")

In [21]:
df["Embarked"].unique()

<StringArray>
['S', 'C', 'Q', 'N']
Length: 4, dtype: str

In [22]:
# N, S, C, Q

In [23]:
df["Embarked_Auto_Cat"] = df["Embarked"].astype("category")

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   PassengerId        891 non-null    int64
 1   Survived           891 non-null    int64
 2   Pclass             891 non-null    int64
 3   Name               891 non-null    str
 4   Sex                891 non-null    str
 5   Age                714 non-null    float64
 6   SibSp              891 non-null    int64
 7   Parch              891 non-null    int64
 8   Ticket             891 non-null    str
 9   Fare               891 non-null    float64
 10  Cabin              204 non-null    str
 11  Embarked           891 non-null    str
 12  Embarked_Auto_Cat  891 non-null    category
dtypes: category(1), float64(2), int64(5), str(5)
memory usage: 84.6 KB

In [25]:
df["Embarked_Auto_Cat"].cat.categories

Index(['C', 'N', 'Q', 'S'], dtype='str')

In [26]:
df["Embarked_Custom_Cat"] = pd.Categorical(df["Embarked"], 
                                           categories = ["N", "C", "S", "Q"],
                                           ordered = True)

In [27]:
df["Embarked_Custom_Cat"].cat.categories

Index(['N', 'C', 'S', 'Q'], dtype='str')

In [29]:
df["Embarked_Custom_Cat"] > 'S'

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890     True
Name: Embarked_Custom_Cat, Length: 891, dtype: bool

In [30]:
df["Embarked_Custom_Cat"].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked_Custom_Cat, dtype: category
Categories (4, str): ['N' < 'C' < 'S' < 'Q']

In [34]:
df["Embarked_Custom_Cat"].cat.codes.head()

0    2
1    1
2    2
3    2
4    2
dtype: int8

In [35]:
df["Sex"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [46]:
df["Sex_Cat_Custom"] = df["Sex"].apply(lambda sex : 1 if sex == "male" else 0)
df["Sex_Cat_Custom"]

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex_Cat_Custom, Length: 891, dtype: int64

In [47]:
df["Sex_Cat_Custom"].unique()

array([1, 0])

In [48]:
df["sex_cat"] = df["Sex"].astype("category").cat.codes

In [49]:
df["sex_cat"].head()

0    1
1    0
2    0
3    0
4    1
Name: sex_cat, dtype: int8

### Date Functionality in Pandas

In [55]:
data = {
  "event" : ["concert", "conference" , "wedding"],
  "date" : ["2026-09-23" , "2026-09-20" , "2026-09-28"]
}

In [56]:
data_df = pd.DataFrame(data)

In [57]:
data_df

        event        date
0     concert  2026-09-23
1  conference  2026-09-20
2     wedding  2026-09-28

In [58]:
data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   event   3 non-null      str
 1   date    3 non-null      str
dtypes: str(2)
memory usage: 180.0 bytes

In [60]:
data_df["date_pandas"] = pd.to_datetime(data_df["date"])

In [61]:
data_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   event        3 non-null      str
 1   date         3 non-null      str
 2   date_pandas  3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(2)
memory usage: 204.0 bytes

In [62]:
data_df

        event        date date_pandas
0     concert  2026-09-23  2026-09-23
1  conference  2026-09-20  2026-09-20
2     wedding  2026-09-28  2026-09-28

In [63]:
data_df["date_pandas"].dt.year

0    2026
1    2026
2    2026
Name: date_pandas, dtype: int32

In [64]:
data_df["date_pandas"].dt.month

0    9
1    9
2    9
Name: date_pandas, dtype: int32

In [65]:
data_df["date_pandas"].dt.weekday

0    2
1    6
2    0
Name: date_pandas, dtype: int32

In [68]:
data_df["date_pandas"].dt.day_name()

0    Wednesday
1       Sunday
2       Monday
Name: date_pandas, dtype: str

In [74]:
data_df['date_pandas'] < '2026-09-25'

0     True
1     True
2    False
Name: date_pandas, dtype: bool

In [75]:
data_df[data_df['date_pandas'] < '2026-09-25']

        event        date date_pandas
0     concert  2026-09-23  2026-09-23
1  conference  2026-09-20  2026-09-20

In [76]:
data_df[data_df["date_pandas"].between('2026-09-20' , '2026-09-25')]

        event        date date_pandas
0     concert  2026-09-23  2026-09-23
1  conference  2026-09-20  2026-09-20

In [78]:
date_df = pd.date_range(start = '2026-09-01' , end = '2026-09-10' , freq = 'D')

In [79]:
date_df

DatetimeIndex(['2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04',
               '2026-09-05', '2026-09-06', '2026-09-07', '2026-09-08',
               '2026-09-09', '2026-09-10'],
              dtype='datetime64[us]', freq='D')

In [80]:
pd.date_range(start = '2026-01-01' , end = '2026-03-23' , freq = 'ME')

DatetimeIndex(['2026-01-31', '2026-02-28'], dtype='datetime64[us]', freq='ME')

In [81]:
pd.date_range(start = '2026-01-01' , end = '2026-03-23' , freq = 'MS')

DatetimeIndex(['2026-01-01', '2026-02-01', '2026-03-01'], dtype='datetime64[us]', freq='MS')

### Date Arithematic

In [82]:
data_df['next_week'] = data_df['date_pandas'] + pd.Timedelta(days=7)

In [83]:
data_df

        event        date date_pandas  next_week
0     concert  2026-09-23  2026-09-23 2026-09-30
1  conference  2026-09-20  2026-09-20 2026-09-27
2     wedding  2026-09-28  2026-09-28 2026-10-05

In [84]:
data_df['time_to_event'] = data_df['date_pandas'] - pd.Timestamp.today()

In [85]:
data_df

        event        date date_pandas  next_week             time_to_event
0     concert  2026-09-23  2026-09-23 2026-09-30  -8 days +15:12:04.419515
1  conference  2026-09-20  2026-09-20 2026-09-27 -11 days +15:12:04.419515
2     wedding  2026-09-28  2026-09-28 2026-10-05  -3 days +15:12:04.419515

In [88]:
pd.Timestamp.today()

Timestamp('2026-09-30 08:48:17.000246')