In [9]:
import pandas as pd

### Series Creation

#### From List

In [10]:
data = [1, 2, 3, 4, 5]
s1 = pd.Series(data)
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [11]:
s2 = pd.Series(data, index = ['a', 'b' , 'c' , 'd' , 'e'] , name = "Scores")
print(s2)

a    1
b    2
c    3
d    4
e    5
Name: Scores, dtype: int64

#### From dictionary

In [12]:
marks = {'manoj' : 23 , 'ram' : 24 , 'sam' :25}
s3 = pd.Series(marks , name = "Marks of DS")
print(s3)

manoj    23
ram      24
sam      25
Name: Marks of DS, dtype: int64

#### From Numpy Array

In [13]:
import numpy as np

In [14]:
array = np.array([10, 20, 30, 40, 50])
s4 = pd.Series(array, index = ['a' , 'b', 'c', 'd' , 'e'])
print(s4)

a    10
b    20
c    30
d    40
e    50
dtype: int64

### Series Attributes

In [15]:
s5 = pd.Series(data = [100, 200, 300, 400, 500] , 
               index = ["a", "b" , "c" , "d" , "e"] , name = "My Series")

In [16]:
print(s5)

a    100
b    200
c    300
d    400
e    500
Name: My Series, dtype: int64

In [17]:
print(s5.name)

My Series

In [18]:
print(s5.index)

Index(['a', 'b', 'c', 'd', 'e'], dtype='str')

In [19]:
print(s5.values)

[100 200 300 400 500]

In [20]:
print(s5.dtype)

int64

In [21]:
print(s5.shape)

(5,)

### Searching Indexing and Accessing

In [1]:
import pandas as pd

In [2]:
s = pd.Series([10, 20, 30, 40, 50] , index = ["a", "b", "c", "d" , "e"])
print(s)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [4]:
print(s.values[0])

10

In [5]:
print(s.values[7])

IndexError: index 7 is out of bounds for axis 0 with size 5

In [6]:
print(s.values[-1])

50

In [7]:
print(s.values[:3])

[10 20 30]

In [8]:
print(s.iloc[0])

10

In [11]:
print(s.iloc[1:3])

b    20
c    30
dtype: int64

In [15]:
print(s.iloc[-1:])

e    50
dtype: int64

In [16]:
print(s.loc['a'])

10

In [17]:
print(s.loc[0])

KeyError: 0

In [18]:
print(s.loc[['a', 'b']])

a    10
b    20
dtype: int64

In [19]:
s1 = pd.Series([10, 20, 30, 40, 50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [21]:
print(s1.loc[2])

30

In [22]:
print(s1.loc[[2 , 3]])

2    30
3    40
dtype: int64

In [23]:
print(s1.loc[1:4])

1    20
2    30
3    40
4    50
dtype: int64

### DataFrames

In [24]:
data = {
  "name" : ["Manoj", "Ram" , "Sam" , "Sri"],
  "age" : [25, 32, 23, 23],
  "city" : ["Hyderabad", "Baanglore", "delhi" , "chennai"]
}

In [25]:
print(data)

{'name': ['Manoj', 'Ram', 'Sam', 'Sri'], 'age': [25, 32, 23, 23], 'city': ['Hyderabad', 'Baanglore', 'delhi', 'chennai']}

In [26]:
df = pd.DataFrame(data)
print(df)

    name  age       city
0  Manoj   25  Hyderabad
1    Ram   32  Baanglore
2    Sam   23      delhi
3    Sri   23    chennai

In [27]:
df

    name  age       city
0  Manoj   25  Hyderabad
1    Ram   32  Baanglore
2    Sam   23      delhi
3    Sri   23    chennai

In [29]:
records = [
  {"name" : "manoj", "age" : 25 , "city" : "Hyderabad"},
  {"name" : "Sam", "age" : 32 , "city" : "Guntur"},
  {"name" : "Ram", "age" : 23 , "city" : "Vizag"}
]

In [30]:
print(records)

[{'name': 'manoj', 'age': 25, 'city': 'Hyderabad'}, {'name': 'Sam', 'age': 32, 'city': 'Guntur'}, {'name': 'Ram', 'age': 23, 'city': 'Vizag'}]

In [31]:
df1 = pd.DataFrame(records)
print(df1)

    name  age       city
0  manoj   25  Hyderabad
1    Sam   32     Guntur
2    Ram   23      Vizag

### From the Numpy Arrays

In [32]:
import numpy as np

In [33]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
df2 = pd.DataFrame(data = arr , columns = ['A', 'B'])
print(df2)

   A  B
0  1  2
1  3  4
2  5  6

### Accessing the data

In [34]:
data = {
  "name" : ["Manoj", "Ram" , "Sam" , "Sri"],
  "age" : [25, 32, 23, 23],
  "city" : ["Hyderabad", "Baanglore", "delhi" , "chennai"]
}
df = pd.DataFrame(data)

In [35]:
df

    name  age       city
0  Manoj   25  Hyderabad
1    Ram   32  Baanglore
2    Sam   23      delhi
3    Sri   23    chennai

In [37]:
df['name']

0    Manoj
1      Ram
2      Sam
3      Sri
Name: name, dtype: str

In [38]:
df[['name', 'age']]

    name  age
0  Manoj   25
1    Ram   32
2    Sam   23
3    Sri   23

In [39]:
df.loc[0]

name        Manoj
age            25
city    Hyderabad
Name: 0, dtype: object

In [40]:
df.iloc[1]

name          Ram
age            32
city    Baanglore
Name: 1, dtype: object

### Working with real dataset

In [42]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [43]:
df = pd.read_csv(titanic_dataset_github_url)

In [44]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [45]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [46]:
df.tail(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [47]:
df.shape

(891, 12)

In [48]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [49]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [52]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [53]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [54]:
df.loc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

### Loading from local CSV file

In [57]:
df = pd.read_csv("titanic.csv")
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [58]:
df.iloc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [62]:
df.loc[3]["Name"]

'Futrelle, Mrs. Jacques Heath (Lily May Peel)'

In [61]:
df.loc[3, "Name"]

'Futrelle, Mrs. Jacques Heath (Lily May Peel)'