In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("titanic.csv")
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [3]:
df.iloc[0]

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [4]:
df.iloc[:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.iloc[-1]

PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [6]:
df.iloc[0, 3]

'Braund, Mr. Owen Harris'

In [7]:
df.iloc[:5 , 3]

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

### Conditional Selection

In [8]:
df["Age"] > 70

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [9]:
df[df["Age"] > 70]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [10]:
older_passengers = df[df["Age"] > 70]
older_passengers.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C

In [11]:
older_passengers.shape

(5, 12)

In [13]:
older_passengers.info()

<class 'pandas.DataFrame'>
Index: 5 entries, 96 to 851
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  5 non-null      int64
 1   Survived     5 non-null      int64
 2   Pclass       5 non-null      int64
 3   Name         5 non-null      str
 4   Sex          5 non-null      str
 5   Age          5 non-null      float64
 6   SibSp        5 non-null      int64
 7   Parch        5 non-null      int64
 8   Ticket       5 non-null      str
 9   Fare         5 non-null      float64
 10  Cabin        2 non-null      str
 11  Embarked     5 non-null      str
dtypes: float64(2), int64(5), str(5)
memory usage: 520.0 bytes

In [15]:
older_passengers.describe()

       PassengerId  Survived    Pclass        Age  SibSp  Parch       Fare
count     5.000000  5.000000  5.000000   5.000000    5.0    5.0   5.000000
mean    438.200000  0.200000  1.800000  73.300000    0.0    0.0  25.936680
std     328.292096  0.447214  1.095445   3.993745    0.0    0.0  18.086844
min      97.000000  0.000000  1.000000  70.500000    0.0    0.0   7.750000
25%     117.000000  0.000000  1.000000  71.000000    0.0    0.0   7.775000
50%     494.000000  0.000000  1.000000  71.000000    0.0    0.0  30.000000
75%     631.000000  0.000000  3.000000  74.000000    0.0    0.0  34.654200
max     852.000000  1.000000  3.000000  80.000000    0.0    0.0  49.504200

In [16]:
older_passengers["Age"].describe()

count     5.000000
mean     73.300000
std       3.993745
min      70.500000
25%      71.000000
50%      71.000000
75%      74.000000
max      80.000000
Name: Age, dtype: float64

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
df[(df["Sex"] == "female") & (df["Survived"] == 1)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

In [35]:
female_survivors_dataset = df[(df["Sex"] == "female") & (df["Survived"] == 1)]

In [36]:
female_survivors_dataset.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [37]:
female_survivors_dataset[['Name','Age']]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]

In [42]:
df.loc[(df["Sex"] == "female") & (df["Survived"] == 1), ['Name', 'Age']]

                                                  Name   Age
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0
..                                                 ...   ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0
875                   Najib, Miss. Adele Kiamie "Jane"  15.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0
887                       Graham, Miss. Margaret Edith  19.0

[233 rows x 2 columns]