In [1]:
import pandas as pd
import numpy as np

In [2]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [3]:
df = pd.read_csv(titanic_dataset_github_url)

In [4]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df_passenger_id = df.set_index("PassengerId")
df_passenger_id.head(2)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [6]:
df_name = df.set_index('Name')
df_name.head(3)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [10]:
df.loc["Braund, Mr. Owen Harris"]

KeyError: 'Braund, Mr. Owen Harris'

In [9]:
df_name.loc['Braund, Mr. Owen Harris']

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                 22.0
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [11]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
subset = df[df['Sex'] == 'male']
subset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S

In [13]:
subset['Age'] = subset['Age'] + 1
subset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S

In [16]:
# This will be more Safer

subset = df[df['Sex'] == 'male'].copy()
subset['Age'] = subset['Age'] + 1
subset.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,23.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,36.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,55.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,3.0,3,1,349909,21.0750,NaN,S

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### set index vs reindex()

In [18]:
df_name = df.set_index('Name')
df_name.head(3)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [20]:
df_name.loc["Heikkinen, Miss. Laina"]

PassengerId                   3
Survived                      1
Pclass                        3
Sex                      female
Age                        26.0
SibSp                         0
Parch                         0
Ticket         STON/O2. 3101282
Fare                      7.925
Cabin                       NaN
Embarked                      S
Name: Heikkinen, Miss. Laina, dtype: object

In [21]:
df_name = df_name.reset_index()
df_name.head()

,Name,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
sales_jan = pd.DataFrame([100, 200, 300] , index=["Store_A" , "Store_B" , "Store_C"] , columns=["Sales"])
sales_jan

         Sales
Store_A    100
Store_B    200
Store_C    300

In [28]:
sales_feb = pd.DataFrame([110, 350] , index=["Store_A" , "Store_C"] , columns=["Sales"])
sales_feb

         Sales
Store_A    110
Store_C    350

In [29]:
common_index = sales_jan.index
print(common_index)

Index(['Store_A', 'Store_B', 'Store_C'], dtype='str')

In [30]:
sales_feb_aligned = sales_feb.reindex(common_index)
sales_feb_aligned

         Sales
Store_A  110.0
Store_B    NaN
Store_C  350.0

In [31]:
sales_diff = sales_feb_aligned["Sales"] - sales_jan["Sales"]
sales_diff

Store_A    10.0
Store_B     NaN
Store_C    50.0
Name: Sales, dtype: float64

In [32]:
sales_feb_aligned = sales_feb.reindex(common_index , fill_value = 0)
sales_feb_aligned

         Sales
Store_A    110
Store_B      0
Store_C    350

In [33]:
sales_diff = sales_feb_aligned["Sales"] - sales_jan["Sales"]
sales_diff

Store_A     10
Store_B   -200
Store_C     50
Name: Sales, dtype: int64

In [35]:
source_a = pd.DataFrame({
  "Product" : ["Laptop", "Ipad" , "Mobile"],
  "Price" : [10000 , 10000 , 1000],
  "Stock" : [23, 45, 67]
})

In [36]:
source_a

  Product  Price  Stock
0  Laptop  10000     23
1    Ipad  10000     45
2  Mobile   1000     67

In [37]:
source_b = pd.DataFrame({
  "Product" : ["Laptop", "Ipad" , "Mobile"],
  "Price" : [999999 , 78390 , 2345]
})

In [38]:
source_b

  Product   Price
0  Laptop  999999
1    Ipad   78390
2  Mobile    2345

In [39]:
stock_diff = source_a["Stock"] - source_b["Stock"]

KeyError: 'Stock'

In [40]:
common_coumns = source_a.columns
print(common_coumns)

Index(['Product', 'Price', 'Stock'], dtype='str')

In [41]:
source_b_aligned = source_b.reindex(columns = common_coumns , fill_value = 0)
source_b_aligned

  Product   Price  Stock
0  Laptop  999999      0
1    Ipad   78390      0
2  Mobile    2345      0

In [43]:
stock_diff = source_a["Stock"] - source_b_aligned["Stock"]
stock_diff

0    23
1    45
2    67
Name: Stock, dtype: int64

### Iterating in pandas

In [44]:
data = pd.DataFrame({
  "Name" : ["Manoj" , "Ram" , "Sai"],
  "Age" : [26 , 32 , 31],
  "City" : ["Hyderabad" , "Chennai" , "Banglore"]
})

In [45]:
data

    Name  Age       City
0  Manoj   26  Hyderabad
1    Ram   32    Chennai
2    Sai   31   Banglore

In [51]:
for index, row in data.iterrows():
  print(f"{index} : {row["Name"]} lives in {row["City"]} and of {row["Age"]} years old")

0 : Manoj lives in Hyderabad and of 26 years old
1 : Ram lives in Chennai and of 32 years old
2 : Sai lives in Banglore and of 31 years old

In [54]:
for row in data.itertuples():
  print(row)
  print(f"{row.Index} : {row.Name} lives in {row.City} and of {row.Age} years old", end = "\n\n")

Pandas(Index=0, Name='Manoj', Age=26, City='Hyderabad')
0 : Manoj lives in Hyderabad and of 26 years old

Pandas(Index=1, Name='Ram', Age=32, City='Chennai')
1 : Ram lives in Chennai and of 32 years old

Pandas(Index=2, Name='Sai', Age=31, City='Banglore')
2 : Sai lives in Banglore and of 31 years old

In [62]:
for col in data.columns:
  print(f"Column : {col}")
  print(data[col].values , end = "\n\n")

Column : Name
<StringArray>
['Manoj', 'Ram', 'Sai']
Length: 3, dtype: str

Column : Age
[26 32 31]

Column : City
<StringArray>
['Hyderabad', 'Chennai', 'Banglore']
Length: 3, dtype: str

In [64]:
list(data.columns)

['Name', 'Age', 'City']

In [65]:
data

    Name  Age       City
0  Manoj   26  Hyderabad
1    Ram   32    Chennai
2    Sai   31   Banglore