In [1]:
import pandas as pd
import numpy as np

In [2]:
# https://github.com/datasciencedojo/datasets
titanic_dataset_github_url = "https://raw.githubusercontent.com/datasciencedojo/datasets/refs/heads/master/titanic.csv"

# https://github.com/mwaskom/seaborn-data/tree/master

iris_dataset_github_url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/iris.csv"

# kaggle
kaggle_link = "https://www.kaggle.com/datasets/yasserh/titanic-dataset/data"

In [3]:
df = pd.read_csv(titanic_dataset_github_url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df["Name"].str.replace("Mr." , "Sir" , regex = False).head()

0                              Braund, Sir Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Sir William Henry
Name: Name, dtype: str

In [7]:
df["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [11]:
df.loc[1]["Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [12]:
df.loc[1, "Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [14]:
start = df.loc[1, "Name"].find("(")
start

27

In [15]:
end = df.loc[1, "Name"].find(")")
end

50

In [21]:
name = df.loc[1, "Name"][:start] + df.loc[1, "Name"][end + 1 : ]
name

'Cumings, Mrs. John Bradley '

In [24]:
df["Name"].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: str

In [28]:
def remove_substring(name):
  start = name.find("(")
  end = name.find(")")
  new_name = name[:start] + name[end + 1:]
  new_name = new_name.strip()
  return new_name

In [29]:
df["Name_Trimmed"] = df["Name"].apply(remove_substring)

In [30]:
df["Name_Trimmed"].head(5)

0      Braund, Mr. Owen HarriBraund, Mr. Owen Harris
1                         Cumings, Mrs. John Bradley
2        Heikkinen, Miss. LainHeikkinen, Miss. Laina
3                       Futrelle, Mrs. Jacques Heath
4    Allen, Mr. William HenrAllen, Mr. William Henry
Name: Name_Trimmed, dtype: str

In [31]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'Name_Trimmed'],
      dtype='str')

In [32]:
df["Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [33]:
df["Name"].replace(r"\(.*\)" , "HELLO" , regex = True).head()

0               Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley HELLO
2                Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath HELLO
4              Allen, Mr. William Henry
Name: Name, dtype: str

In [34]:
df["Name"].replace(r"\(.*\)" , "" , regex = True).head()

0          Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley
2           Heikkinen, Miss. Laina
3    Futrelle, Mrs. Jacques Heath
4         Allen, Mr. William Henry
Name: Name, dtype: str

### Split and Access Elements

In [35]:
df["Name"][0]

'Braund, Mr. Owen Harris'

In [ ]:
df["Name"].str.split(",")[0]

['Braund', ' Mr. Owen Harris']

In [38]:
df["Name"].str.split(" ")[0]

['Braund,', 'Mr.', 'Owen', 'Harris']

In [39]:
df["Name"].str.split(" ").str[0]

0         Braund,
1        Cumings,
2      Heikkinen,
3       Futrelle,
4          Allen,
          ...
886     Montvila,
887       Graham,
888     Johnston,
889         Behr,
890       Dooley,
Name: Name, Length: 891, dtype: object

### Strip Spaces

In [40]:
df["Name"][0]

'Braund, Mr. Owen Harris'

In [42]:
df["Name"].str.strip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [43]:
df["Name"].str.lstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [44]:
df["Name"].str.rstrip()

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

### Find Poisition of substring

In [45]:
df["Name"].str.find("Mr.")

0      8
1     -1
2     -1
3     -1
4      7
      ..
886   -1
887   -1
888   -1
889    6
890    8
Name: Name, Length: 891, dtype: int64

In [46]:
df["Name"].str.contains("Mr.")

0       True
1       True
2      False
3       True
4       True
       ...
886    False
887    False
888    False
889     True
890     True
Name: Name, Length: 891, dtype: bool

In [48]:
count = df["Name"].str.contains("Mr.").sum()
print(count)

647

In [49]:
data = pd.DataFrame({
  "Name" : ["Manoj", "Sai" , "Ravi" , "Pavan" , "Sonu"],
  "email" : ["man@gmail.com", "s@gmail.com" , "pas@gmail.com" , "rav@gmail.com" , "xc@gmail.com"]
})

In [50]:
data

    Name          email
0  Manoj  man@gmail.com
1    Sai    s@gmail.com
2   Ravi  pas@gmail.com
3  Pavan  rav@gmail.com
4   Sonu   xc@gmail.com

In [51]:
data["Name"].str.pad(width = 15, fillchar = "*" , side = "left")

0    **********Manoj
1    ************Sai
2    ***********Ravi
3    **********Pavan
4    ***********Sonu
Name: Name, dtype: str